This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./main_thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main_thesis.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file main_thesis.acr....done (6 lines written, 0 warnings).
Output written in main_thesis.acr.
Transcript written in main_thesis.alg.
